# This file was generated by the {rix} R package v0.3.1 on 2024-03-05
# with following call:
# >rix(r_pkgs = c("rio",
#  > "data.table",
#  > "miceadds",
#  > "margins",
#  > "sandwich",
#  > "glue",
#  > "modelsummary",
#  > "lubridate",
#  > "lme4"),
#  > r_ver = "fa9a51752f1b5de583ad5213eb621be071806663")
# It uses nixpkgs' revision fa9a51752f1b5de583ad5213eb621be071806663 for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
# (Manual modifications were made to add python packages)
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/43d259f8d726113fac056e8bb17d5ac2dea3e0a8.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) rio data_table miceadds margins sandwich glue modelsummary lubridate lme4;
};
  my-python-packages = ps: with ps; [
    beautifulsoup4
    requests
    lxml
    ipython
    radian
  ];
  tex = (pkgs.texlive.combine {
  inherit (pkgs.texlive) scheme-small ;
});
 git_archive_pkgs = [ (pkgs.rPackages.buildRPackage {
    name = "Matrix";
    src = pkgs.fetchzip {
      url = "https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-2.tar.gz";
      sha256 = "sha256-bmc6Vfi4dj3LS/TZUbWYmbFFtQcbEgYxrQXRCT1GrwE=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) lattice;
    };
  })];
 system_packages = builtins.attrValues {
  inherit (pkgs) R ;
};
  in
  pkgs.mkShell {
    buildInputs = [  rpkgs pkgs.gnumake system_packages (pkgs.python3.withPackages my-python-packages) ];
  }
