# This file was generated by the {rix} R package v0.3.1 on 2023-09-17
# with following call:
# >rix(r_ver = "fd03a8aa6db25f12ed3799b37170e2933ecd5d4f",
#  > r_pkgs = c("rio",
#  > "data.table",
#  > "miceadds",
#  > "margins",
#  > "sandwich",
#  > "glue",
#  > "modelsummary",
#  > "lubridate"),
#  > overwrite = T)
# It uses nixpkgs' revision fd03a8aa6db25f12ed3799b37170e2933ecd5d4f for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/fd03a8aa6db25f12ed3799b37170e2933ecd5d4f.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) rio data_table miceadds margins sandwich glue modelsummary lubridate flextable kableExtra;
};
  my-python-packages = ps: with ps; [
    beautifulsoup4
    requests
    lxml
    ipython
    radian
  ];
  tex = (pkgs.texlive.combine {
  inherit (pkgs.texlive) scheme-small ;
});
 system_packages = builtins.attrValues {
  inherit (pkgs) R ;
};
  in
  pkgs.mkShell {
    buildInputs = [  rpkgs pkgs.gnumake system_packages (pkgs.python3.withPackages my-python-packages) ];
  }
